name: time_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  boardview: ^0.2.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
